apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: orders-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: orders
  minReplicas: 1
  maxReplicas: 6
  metrics:
    - type: Object
      object:
        describedObject:
          apiVersion: v1
          kind: Service
          name: orders
        metric:
          name: rps
        target:
          # Escala para manter rps <= 50 (valor alvo); ajuste conforme desejado
          type: Value
          value: "50"
